name: Test workflow

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Print Text
        run: |
          echo "Hello"
          echo "Hello" >> artifact.txt
          
      - name: Upload Artifact 
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: |
            artifact.txt